### numpy
* Numerical python or numeric python
* NumPy is a programming language that deals with multidimensional arrays and matrices
* NumPy supports a large number of mathematical operations
* **Why use NumPy**
* NumPy is memory effeciency meaning it can handle the vast amount of data more accessible than any other library
* especially for matrix multiplication and reshapping
* on top of that,numPy is fast.In fact tensor flow and scikt
### how to install NumPy
* **NumPy is installed by default in anaconda**


In [1]:
import numpy as np


In [2]:
print(np.__version__)

1.19.2


In [6]:
print(np.array([[1,2,3,4],[5,6,7,8]]))

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
print(np.array([[1,2,3,4],[5,6,7]]))

[list([1, 2, 3, 4]) list([5, 6, 7])]


<ipython-input-7-ed2dd7be7659>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  print(np.array([[1,2,3,4],[5,6,7]]))


In [11]:
# mathematical operations
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a-b)

[ 6  8 10 12]
[-4 -4 -4 -4]


In [12]:
A=np.array([[1,2,3,4],[5,6,7,8]])
print(A)
print(A.dtype)

[[1 2 3 4]
 [5 6 7 8]]
int32


In [15]:
A=np.array([[1,2,3,4],[5,6,7,8]])
print(np.shape(A))
print(A.dtype)

(2, 4)
int32


In [16]:
#numpy zeros
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
#numpy ones
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
A=np.array([[1,2,3,4],[5,6,7,8]])
A.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
# flatten
print(A)
A.flatten()

[[1 2 3 4]
 [5 6 7 8]]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
# h stack
a1=np.array([1,2,3,4])
a2=np.array([9,10,11,12])
print(a1)
print(a2)
print(np.hstack((a1,a2)))

[1 2 3 4]
[ 9 10 11 12]
[ 1  2  3  4  9 10 11 12]


In [25]:
# v stack
a1=np.array([1,2,3,4])
a2=np.array([9,10,11,12])
print(a1)
print(a2)
print(np.vstack((a1,a2)))

[1 2 3 4]
[ 9 10 11 12]
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [27]:
# hstack and vstack()
a1=np.array([1,2,3,4])
a2=np.array([9,10,11,12])
print(a1)
print(a2)
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))

[1 2 3 4]
[ 9 10 11 12]
[ 1  2  3  4  9 10 11 12]
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [36]:
# mean,median
a1=np.array([1,2,3,4])
print(a1)
print(a1.mean())
print(np.median(a1))

[1 2 3 4]
2.5
2.5


In [37]:
# mod
print(np.mod(2,3))

2


In [40]:
d=np.random.randint(1,30,(2,2))
d

array([[ 7, 13],
       [13, 15]])

In [41]:
np.random.normal(5,7,5)

array([13.50245971,  3.21970357,  1.05024442,  3.78255355,  8.57081792])

In [42]:
a1=np.array([1,2,3])
print(a1.min())
print(a1.max())

1
3


In [46]:
# transpose
a1=np.array(([1,2,3],[9,10,11]))
print(a1)
print(a1.T)

[[ 1  2  3]
 [ 9 10 11]]
[[ 1  9]
 [ 2 10]
 [ 3 11]]


In [47]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
# dot operation
a1=np.array([1,2,3,4])
a2=np.array([9,10,11,12])
a1.dot(a2)

110

In [50]:
# power
a1=np.array([1,2,3,4])
np.array([a1,pow(a1,2)])

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [57]:
# repeat
a1=np.repeat([1,2,3,4],2)
a1


array([1, 1, 2, 2, 3, 3, 4, 4])

In [60]:
# repeat
a1=np.repeat([1,2,3,4],2)
print(a1*2)

[2 2 4 4 6 6 8 8]


In [59]:
# arange
# syntax-->(start,stop,step)
np.arange(1,5,1)

array([1, 2, 3, 4])

In [61]:
# linspace(default=50)
# syntax(start,stop,num,endpoint)
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [62]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [66]:
a1=np.array(([1,2,3],[9,10,11]))
print(a1)
a1[:,1]

[[ 1  2  3]
 [ 9 10 11]]


array([ 2, 10])